feat: search component and browse rework
rivenmedia/riven-frontend pull request #150
Opened 2024-10-24 15:23 UTC by Gaisberg

chore: improve nprogress coloring
refactor: use strong typing where logic implemented
chore: add shadcn-svelte components

2024-10-24 16:08 UTC, AyushSehrawat requested changes

2024-10-24 16:08 UTC, AyushSehrawat commented on package.json
https://github.com/rivenmedia/riven-frontend/blob/4118e74862b5f600cb2d9eb693a071d06708d9e6/package.json

Use this file

2024-10-24 16:08 UTC, AyushSehrawat commented on src/app.css
> +}
Revert back to previous

```css
.no-scrollbar::-webkit-scrollbar {
	display: none;
}
```

2024-10-24 16:08 UTC, AyushSehrawat commented on src/lib/components/home-items.svelte
> -				</a>
They are 404 but are required in future, so keep them (can do href="#" if you want)

Will be used to show movies from hot/trending with pagination and stuff

2024-10-24 16:08 UTC, AyushSehrawat commented on src/lib/components/media-item.svelte
> +	const baseUrl = 'https://images.metahub.space/poster/medium/';
switch to small, we don't need medium size images, it takes more network to load for no benefit

2024-10-24 16:08 UTC, AyushSehrawat commented on src/lib/components/media-item.svelte
> +	class="relative block h-full w-full overflow-hidden rounded-lg shadow-lg transition-all duration-300 ease-in-out hover:scale-105 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-
focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-background

Not required on <a> links imo

2024-10-24 16:08 UTC, AyushSehrawat commented on tailwind.config.ts
> -				'6/7': '85.7142857%'
add these back, i think you running the commands again overwrote them

2024-10-24 16:08 UTC, AyushSehrawat commented on src/routes/+layout.svelte
> -	// }
No notifications ?

2024-10-24 16:08 UTC, AyushSehrawat commented on src/lib/utils/search.ts
https://www.cmdk-sv.com/
https://www.shadcn-svelte.com/docs/components/command

You can use these for adding search functionality

Add this first on cmd + k or ctrl k, so a search box pop up. Then in header add a button (with just borders), on clicking it opens the search

For reactivity, you can use writables and if you want to change those writables in some other files you can use setContext and getContext. Look into them in svelte docs

2024-10-24 16:08 UTC, AyushSehrawat commented on src/routes/browse/schema.ts
schemas go to lib folder, probably make it lib/schema/browse.ts or something

2024-10-24 16:08 UTC, AyushSehrawat commented on src/lib/components/header.svelte
> +	<Dialog.Content class="p-0 sm:max-w-[600px] [&>button]:hidden">
`p-0 sm:max-w-[600px] [&>button]:hidden` See if removing `p-0 [&>button]:hidden` makes any difference. If not then remove them

2024-10-24 16:08 UTC, AyushSehrawat commented on src/lib/components/header.svelte
> +			//pass
remove try catch or do catch (e) { console.error(e) }

2024-10-25 05:38 UTC, Gaisberg commented on src/routes/+layout.svelte
> -	// }
this logic is deprecated

2024-10-25 05:38 UTC, Gaisberg commented on src/lib/utils/search.ts
this is a future improvement

2024-10-26 06:16 UTC, AyushSehrawat approved these changes

2024-10-26 06:44 UTC, merged